/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package st_lab;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author bishu
 */
public class ST_LAB extends javax.swing.JFrame {

    private FTest F = new FTest();
    private STest S = new STest();

    /**
     * Creates new form ST_LA
     */
    public ST_LAB() {
        initComponents();
        ImageIcon icon = new ImageIcon(System.getProperty("user.dir") + "\\src\\icons\\test_icon.gif");
        setIconImage(icon.getImage());
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        robworst = new javax.swing.JButton();
        robust = new javax.swing.JButton();
        worst = new javax.swing.JButton();
        boundary = new javax.swing.JButton();
        eqcl = new javax.swing.JButton();
        dtable = new javax.swing.JButton();
        ceg = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        paths = new javax.swing.JButton();
        cfg = new javax.swing.JButton();
        dd = new javax.swing.JButton();
        cc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software Testing");

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        label1.setText("Software Testing");

        jTabbedPane1.setBackground(java.awt.SystemColor.activeCaption);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setName(""); // NOI18N

        robworst.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        robworst.setText("Robust Worst-case");
        robworst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robworstMouseClicked(evt);
            }
        });

        robust.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        robust.setText("Robustness");
        robust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robustMouseClicked(evt);
            }
        });

        worst.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        worst.setText("Worst-case");
        worst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                worstMouseClicked(evt);
            }
        });

        boundary.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        boundary.setText("Boundary Value");
        boundary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boundaryMouseClicked(evt);
            }
        });

        eqcl.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        eqcl.setText("Equivalence Class");
        eqcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eqclMouseClicked(evt);
            }
        });

        dtable.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        dtable.setText("Decision Table");
        dtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtableMouseClicked(evt);
            }
        });

        ceg.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        ceg.setText("Cause Effect Graph");
        ceg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cegMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ceg, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtable, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqcl, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robworst, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robust, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boundary, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(worst, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(boundary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(robust, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(worst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(robworst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eqcl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dtable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ceg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jDesktopPane2.setLayer(robworst, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(robust, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(worst, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(boundary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(eqcl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(dtable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(ceg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Functional Testing", jDesktopPane2);

        paths.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        paths.setText("Independent Paths");
        paths.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathsMouseClicked(evt);
            }
        });

        cfg.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cfg.setText("Control Flow Graph");
        cfg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cfgMouseClicked(evt);
            }
        });

        dd.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        dd.setText("DD Path Graph");
        dd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddMouseClicked(evt);
            }
        });

        cc.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        cc.setText("Cyclomatic Complexity");
        cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paths, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cfg, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cfg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paths, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jDesktopPane3.setLayer(paths, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(cfg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(dd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(cc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Structural Testing", jDesktopPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jTabbedPane1)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boundaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boundaryMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("b");
        F.setVisible(true);
    }//GEN-LAST:event_boundaryMouseClicked

    private void robustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robustMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("r");
        F.setVisible(true);
    }//GEN-LAST:event_robustMouseClicked

    private void worstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_worstMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("w");
        F.setVisible(true);
    }//GEN-LAST:event_worstMouseClicked

    private void robworstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robworstMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("rw");
        F.setVisible(true);
    }//GEN-LAST:event_robworstMouseClicked

    private void ccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccMouseClicked
        // TODO add your handling code here:
        this.dispose();
        S.setTest("cc");
        S.setVisible(true);
    }//GEN-LAST:event_ccMouseClicked

    private void cfgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cfgMouseClicked
        // TODO add your handling code here:
        this.dispose();
        S.setTest("cfg");
        S.setVisible(true);
    }//GEN-LAST:event_cfgMouseClicked

    private void ddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddMouseClicked
        // TODO add your handling code here:
        this.dispose();
        S.setTest("dd");
        S.setVisible(true);
    }//GEN-LAST:event_ddMouseClicked

    private void pathsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        S.setTest("p");
        S.setVisible(true);
    }//GEN-LAST:event_pathsMouseClicked

    private void eqclMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eqclMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("eq");
        F.setVisible(true);
    }//GEN-LAST:event_eqclMouseClicked

    private void dtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtableMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("dt");
        F.setVisible(true);
    }//GEN-LAST:event_dtableMouseClicked

    private void cegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cegMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F.setTest("ceg");
        F.setVisible(true);
    }//GEN-LAST:event_cegMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ST_LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ST_LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ST_LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ST_LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ST_LAB st = new ST_LAB();
                st.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boundary;
    private javax.swing.JButton cc;
    private javax.swing.JButton ceg;
    private javax.swing.JButton cfg;
    private javax.swing.JButton dd;
    private javax.swing.JButton dtable;
    private javax.swing.JButton eqcl;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JButton paths;
    private javax.swing.JButton robust;
    private javax.swing.JButton robworst;
    private javax.swing.JButton worst;
    // End of variables declaration//GEN-END:variables

}
